

CREATE PROC FI_SP_IncBeneficiario
    @Nome         VARCHAR (50) ,
    @IdCliente     BIGINT,
	@CPF		   VARCHAR (15)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, IDCLIENTE, CPF) 
	VALUES (@NOME, @IDCLIENTE,@CPF)

	SELECT SCOPE_IDENTITY()
END